config/routes.rb
Rails.application.routes.draw do
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  
 scope module: :public do 
 root to:'homes#top'
 get '/about' => 'homes#about'
 resources :items , only: [:index, :show]
 get 'customers/my_page' => 'customers#show'
 get 'customers/information/edit' => 'customers#edit'
 patch 'customers/information' => 'customers#update'
 get 'customers/confirm' => 'customers#confirm'
 patch 'customers/withdraw' => 'customers#withdraw'
 delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
 resources :cart_items , only: [:index, :update, :destroy, :create]
 post 'orders/confirm' => 'orders#confirm'
 get 'orders/finish' => 'orders#finish'
 resources :orders , only: [:new, :create, :index, :show]
 resources :addresses , only: [:index, :edit, :create, :update, :destroy]
 get "customers" => redirect("/customers/sign_up")
 get '/genre/search' =>'genre_searches#search'
 get "customers" => redirect("/customers/sign_up")
 end
 
 
 namespace :admin do
 get '/' => 'homes#top'
 resources :items , only: [:index, :new, :create, :show,:edit, :update]
 resources :genres , only: [:index, :create, :edit, :update]
 resources :customers , only: [:index, :show, :edit, :update]
 resources :orders , only: [:show, :update]
 resources :order_details , only: [:update]
 end
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

 has_many :cart_items, dependent: :destroy
 has_many :items,through: :cart_item, dependent: :destroy
 has_many :orders, dependent: :destroy
 has_many :addresses, dependent: :destroy

 validates :email, presence: true, uniqueness: true
 validates :post_code, presence: true
 validates :address, presence: true
 validates :phone_number, presence: true
 validates :password, presence: true, length: { minimum: 6 }, on: :create # ユーザー新規登録時のみバリデーションを実行 
 validates :password_confirmation, presence: true, length: { minimum: 6 }, on: :create # ユーザー新規登録時のみバリデーションを実行 
 
 validates :last_name, :first_name, :last_name_kana, :first_name_kana, presence: { message: 'は必須項目です。' }
 validates :last_name, :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は全角で入力して下さい。' }
 validates :last_name_kana, :first_name_kana, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。' }
 
 # is_activeがtrueならfalseを返すようにしている
  def active_for_authentication?
    super && (is_active == true)
  end
 
  def full_name
    "#{last_name} #{first_name}"
  end

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @customers = Customer.page(params[:page])
  end
  
  def show
    @customer = Customer.find(params[:id])
  end
  
  def edit
    @customer = Customer.find(params[:id])
  end
  
  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to admin_customer_path(@customer)
    else
      render :edit
    end
  end
  
  private
  
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :post_code, :address, :phone_number, :email, :is_active)
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/views/admin/customers/edit.erb
<div class="container">
  <div class="row">
    <h2 class="my-4 px-4", style="background-color: #FFDBC9;">顧客編集画面</h2>
  </div>
    
    <%= form_with model: @customer, url: admin_customer_path(@customer) do |f| %>
    
      <div class="row col-form-label-lg">
        <div class="col-1"></div>
        <div class="col-3">
          <%= f.label :会員id %>
        </div>
        <div class="col-3">
          <%= @customer.id %>
        </div>
      </div>
      
      <div class="row col-form-label-lg">
        <div class="col-1"></div>
        <div class="col-3">
          <%= f.label :氏名 %>
        </div>
        <div class="col-3">
          <%= f.text_field :last_name, autofocus: true, placeholder: "令和", autocomplete: "last_name" %>
        </div>
        <div class="col-1">
          <%= f.text_field :first_name, autofocus: true, placeholder: "道子", autocomplete: "first_name" %>
        </div>
      </div>
    
      <div class="row col-form-label-lg">
        <div class="col-1"></div>
        <div class="col-3">
          <%= f.label :フリガナ %>
        </div>
        <div class="col-3">
          <%= f.text_field :last_name_kana, autofocus: true, placeholder: "レイワ", autocomplete: "last_name_kana" %>
        </div>
        <div class="col-1">
          <%= f.text_field :first_name_kana, autofocus: true, placeholder: "ミチコ", autocomplete: "first_name_kana" %>
        </div>
      </div>
      
      <div class="row col-form-label-lg">
        <div class="col-1"></div>
        <div class="col-3">
          <%= f.label :"郵便番号(ハイフンなし)" %>
        </div>
        <div class="col-3">
          <%= f.text_field :post_code, autofocus: true, placeholder: "0000000", autocomplete: "post_code" %>
        </div>
      </div>
      
      <div class="row col-form-label-lg">
        <div class="col-1"></div>
        <div class="col-3">
          <%= f.label :住所 %>
        </div>
        <div class="col-3">
          <%= f.text_field :address, autofocus: true, placeholder: "東京都渋谷区代々木神園町0-0", autocomplete: "address", size: "40" %>
        </div>
      </div>
      
      <div class="row col-form-label-lg">
        <div class="col-1"></div>
        <div class="col-3">
          <%= f.label :"電話番号(ハイフンなし)" %>
        </div>
        <div class="col-3">
          <%= f.text_field :phone_number, autofocus: true, placeholder: "0000000000", autocomplete: "phone_number" %>
        </div>
      </div>
      
      <div class="row col-form-label-lg">
        <div class="col-1"></div>
        <div class="col-3">
          <%= f.label :メールアドレス %>
        </div>
        <div class="col-3">
          <%= f.email_field :email, autofocus: true, placeholder: "sample@example.com", autocomplete: "email", size: "40" %>
        </div>
      </div>
      
      <div class="row col-form-label-lg">
        <div class="col-1"></div>
        <div class="col-3">
          <%= f.label :is_active, '会員ステータス' %>
        </div>
        <div class="col-3">
        <%= f.radio_button :is_active, true, checked: @customer.is_active == true %>
        <%= f.label :is_active, '有効' %>
        <%= f.radio_button :is_active, false, checked: @customer.is_active == false %>
        <%= f.label :is_active, '退会' %>
        </div>
      </div>
    	
    	<div class="row mt-3 mb-5">
        <div class="col"></div>
        <%= f.submit "変更を保存", class: "btn btn-success" %>
        <div class="col"></div>
    　</div>
    <% end %>
</div>

app/views/admin/customers/index.erb
<div class="container">
  <div class="row">
    <h2 class="px-4 my-4", style="background-color: #FFDBC9;">会員一覧</h2>
  </div>
    
    <div class="row">
      <table class="table my-5 table-hover">
        <thead style="background-color: #FFDBC9;">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer) %></td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_active %>
                <strong class="text-success">有効</strong>
               <% else %>
                <strong class="text-muted">退会</strong>
              <% end %>
            </td>
          </tr>
          <% end %>
          <%= paginate @customers %>
        </tbody>
      </table>
    </div>
    <div class="row">
    <div class="col"></div>
      <%= paginate @customers %>
    <div class="col"></div>
  </div>
</div>

app/views/admin/customers/show.erb
<div class="container">
  <div class="row">
    <h2 class="px-4 my-4", style="background-color: #FFDBC9;"><%= @customer.last_name %><%= @customer.first_name %>さんの会員詳細</h2>
  </div>
  
  <div class="row", style="font-size: 23px;">
    <div class="col-3">
      <p>会員ID</p>
    </div>
    <div class="col-3">
      <%= @customer.id %>
    </div>
  </div>
  
  <div class="row", style="font-size: 23px;">
    <div class="col-3">
      <p>氏名</p>
    </div>
    <div class="col-3">
      <%= @customer.last_name %> <%= @customer.first_name %>
    </div>
  </div>
  
  <div class="row", style="font-size: 23px;">
    <div class="col-3">
      <p>カナ</p>
    </div>
    <div class="col-3">
      <%= @customer.last_name_kana %> <%= @customer.first_name_kana %>
    </div>
  </div>
  
  <div class="row", style="font-size: 23px;">
    <div class="col-3">
      <p>郵便番号</p>
    </div>
    <div class="col-3">
      <%= @customer.post_code %>
    </div>
  </div>
  
  <div class="row", style="font-size: 23px;">
    <div class="col-3">
      <p>住所</p>
    </div>
    <div class="col-3">
      <%= @customer.address %>
    </div>
  </div>
  
  <div class="row", style="font-size: 23px;">
    <div class="col-3">
      <p>電話番号</p>
    </div>
    <div class="col-3">
      <%= @customer.phone_number %>
    </div>
  </div>
  
  <div class="row", style="font-size: 23px;">
    <div class="col-3">
      <p>メールアドレス</p>
    </div>
    <div class="col-3">
      <%= @customer.email %>
    </div>
  </div>
  
  <div class="row", style="font-size: 23px;">
    <div class="col-3">
      <p>会員ステータス</p>
    </div>
    <div class="col-3">
      <% if @customer.is_active %>
       <strong class="text-success">有効</strong>
      <% else %>
       <strong class="text-muted">退会</strong>
      <% end %>
    </div>
  </div>
  
  <div class="row mt-3 mb-5">
    <div class="col-3"></div>
    <%= link_to "編集する", edit_admin_customer_path(@customer), class:"btn btn-success mr-5" %>
    <%= link_to "注文履歴一覧を見る",admin_path, class:"btn btn-primary ml-5" %>
  </div>
</div>