config/routes.rb
Rails.application.routes.draw do
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  
 scope module: :public do 
 root to:'homes#top'
 get '/about' => 'homes#about'
 resources :items , only: [:index, :show]
 get 'customers/my_page' => 'customers#show'
 get 'customers/information/edit' => 'customers#edit'
 patch 'customers/information' => 'customers#update'
 get 'customers/confirm' => 'customers#confirm'
 patch 'customers/withdraw' => 'customers#withdraw'
 delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
 resources :cart_items , only: [:index, :update, :destroy, :create]
 post 'orders/confirm' => 'orders#confirm'
 get 'orders/finish' => 'orders#finish'
 resources :orders , only: [:new, :create, :index, :show]
 resources :addresses , only: [:index, :edit, :create, :update, :destroy]
 get "customers" => redirect("/customers/sign_up")
 get '/genre/search' =>'genre_searches#search'
 get "customers" => redirect("/customers/sign_up")
 end
 
 
 namespace :admin do
 get '/' => 'homes#top'
 resources :items , only: [:index, :new, :create, :show,:edit, :update]
 resources :genres , only: [:index, :create, :edit, :update]
 resources :customers , only: [:index, :show, :edit, :update]
 resources :orders , only: [:show, :update]
 resources :order_details , only: [:update]
 end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         validates :email, presence: true
         validates :password, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.add_tax_price * amount
  end
  
  def self.calculate_total_price(cart_items)
    cart_items.inject(0) { |sum, item| sum + item.subtotal }
  end

  validates :item_id, presence: true
  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

 has_many :cart_items, dependent: :destroy
 has_many :items,through: :cart_item, dependent: :destroy
 has_many :orders, dependent: :destroy
 has_many :addresses, dependent: :destroy

 validates :email, presence: true, uniqueness: true
 validates :post_code, presence: true
 validates :address, presence: true
 validates :phone_number, presence: true
 validates :password, presence: true, length: { minimum: 6 }, on: :create # ユーザー新規登録時のみバリデーションを実行 
 validates :password_confirmation, presence: true, length: { minimum: 6 }, on: :create # ユーザー新規登録時のみバリデーションを実行 
 
 validates :last_name, :first_name, :last_name_kana, :first_name_kana, presence: { message: 'は必須項目です。' }
 validates :last_name, :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は全角で入力して下さい。' }
 validates :last_name_kana, :first_name_kana, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。' }
 
 # is_activeがtrueならfalseを返すようにしている
  def active_for_authentication?
    super && (is_active == true)
  end
 
  def full_name
    "#{last_name} #{first_name}"
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  enum status: { on_sale: 0, off_sale: 1 }
  
  has_many :cart_items, dependent: :destroy
  has_many :customers,through: :cart_items , dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders,through: :order_details , dependent: :destroy
  
  belongs_to :genre
  
  def add_tax_price
    (self.price * 1.10).round
  end
  
  def self.active_items_count
    where(is_active: true).count
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :items,through: :order_details, dependent: :destroy
  
  belongs_to :customer
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, shipped: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
  def subtotal
    price * amount
  end
  
  enum making_status: { unprovable: 0, awaiting_production: 1, in_production: 2, production_completed: 3}
  
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController

  def index
    @genre = Genre.new
    @genres = Genre.all
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      redirect_to request.referer,notice: '保存に失敗しました'
    end
  end


  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "Genre was successfully updated."
      redirect_to admin_genres_path
    else
      render:edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end


end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   before_action :authenticate_admin!

   def top
     @orders = Order.page(params[:page])
   end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      flash.now[:alert] = "保存に失敗しました"
      render :new
    end
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def index
    @items = Item.page(params[:page])
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
    redirect_to admin_item_path(@item.id)
    else
      render:edit
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :status, :is_active)
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  
  
  def show
    @order = Order.find(params[:id])
    @order_details = OrderDetail.where(order_id: @order.id)
  end
  
  def update
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    if @order.update(order_params)
       @order_details.update_all(making_status:'awaiting_production') if @order.status == "payment_confirmation"
      flash[:notice] = "注文ステータスを更新しました"
      redirect_to admin_order_path
    else
      flash[:alert] = "注文ステータスの更新に失敗しました"
      render :show
    end
  end
  
  
  private
  
  def order_params
    params.require(:order).permit(:status)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/oder_details_helper.rb
module Admin::OderDetailsHelper
end

app/helpers/admin/oders_helper.rb
module Admin::OdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/homes/top.erb
<div class="container">
  <div class="row">
    <h2 class="px-4 my-4", style="background-color: #FFDBC9;">注文履歴</h2>
  </div>
  <div class="row">
      <table class="table table-hover my-5">
       <thead style="background-color: #FFDBC9;">
          <tr>
            <th class="col-3">購入履歴</th>
            <th>購入者</th>
            <th>注文個数</th>
            <th>注文ステータス</th>
          </tr>
        </thead>
        <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td>
              <%= link_to admin_order_path(order), data: {"turbolinks" => false} do %>
              <%= order.created_at.strftime("%Y/%m/%d %H:%M:%S") %>
              <% end %>
              </td>
            <td><%= order.customer.last_name %>&nbsp;<%= order.customer.first_name %></td>
            <td><%= order.order_details.sum(:amount) %></td>
            <td><%= order.status_i18n  %></td>
          </tr>
        <% end %>
        </tbody>
      </table>
  </div>
  <div class="row">
    <div class="col"></div>
      <%= paginate @orders %>
    <div class="col"></div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container", style="font-size: 20px;">
  <div class="row">
    <h2 class="px-4 my-4", style="background-color: #FFDBC9;">注文履歴詳細</h2>
  </div>
  <div class="row">
      <div class="col-10">
        <table>
          <tbody>
            <tr>
              <th scope="row" style="width: 50%">購入者</th>
              <td>
                <%= link_to admin_customer_path(@order.customer) do %>
                <%= @order.customer.last_name %>&nbsp;<%= @order.customer.first_name %>
                <% end %>
                </td>
            </tr>
            <tr>
              <th scope="row" style="width: 50%">注文日</th>
              <td><%= @order.created_at.strftime("%Y/%m/%d") %></td>
            </tr>
            <tr>
              <th scope="row" style="width: 50%">配送先</th>
              <td>〒<%= @order.post_code + " " + @order.address %></td>
            </tr>
            <tr>
              <th scope="row" style="width: 50%"></th>
              <td><%= @order.name %></td>
            </tr>

            <tr>
              <th scope="row" style="width: 50%">支払方法</th>
              <td><%= @order.payment_method_i18n %></td>
            </tr>
             <tr>
              <%= form_with model: @order, url: admin_order_path(@order),method: :patch, local: true do |f| %> 
              <th scope="row" style="width: 50%">注文ステータス</th>
              <td>
                <%= f.select :status, Order.statuses_i18n.invert,{ class: "custom-select w-100"} %>
                <%= f.submit "更新",class:"btn btn-success" %>
              </td>
              <% end %>
            </tr>
          </tbody>
        </table>
        <table class="table table-hover my-5">
          <thead style="background-color: #FFDBC9;">
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>制作ステータス</th>
            <th></th>
          </thead>
          <% @sum = 0 %>
          <% @order_details.each do |order_detail| %>
          <tbody>
            <td><%= order_detail.item.name %></td>
            <td><%= order_detail.price.to_s(:delimited) %></td>
            <td><%= order_detail.amount.to_s(:delimited) %></td>
            <td><%= order_detail.subtotal.to_s(:delimited) %></td>
            <%= form_with model: order_detail, url: admin_order_detail_path(order_detail),method: :patch do |f| %> 
            <td> <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert, { class: "custom-select w-100"}%></td>
            <td> <%= f.submit "更新",class:"btn btn-success" %></td>
            <% end %>
            <% @sum += order_detail.subtotal %>
          <% end %>
          </tbody>
        </table>
        <table>
          <tbody>
            <tr>
              <th>商品合計</th>
              <td><%= @sum.to_s(:delimited) %>円</td>
            </tr>
            <tr>
              <th>送料</th>
              <td><%= @order.shipping_cost.to_s(:delimited) %>円</td>
            </tr>
            <tr>
              <th>請求金額</th>
              <td><%= @order.total_payment.to_s(:delimited) %>円</td>
            </tr>
          </tbody>
        </table>
      </div>
  </div>
</div>