config/routes.rb
Rails.application.routes.draw do
devise_for :customers,skip: [:passwords], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}

devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  
 scope module: :public do 
 root to:'homes#top'
 get '/about' => 'homes#about'
 resources :items , only: [:index, :show]
 get 'customers/my_page' => 'customers#show'
 get 'customers/information/edit' => 'customers#edit'
 patch 'customers/information' => 'customers#update'
 get 'customers/confirm' => 'customers#confirm'
 patch 'customers/withdraw' => 'customers#withdraw'
 delete 'cart_items/destroy_all' => 'cart_items#destroy_all'
 resources :cart_items , only: [:index, :update, :destroy, :create]
 post 'orders/confirm' => 'orders#confirm'
 get 'orders/finish' => 'orders#finish'
 resources :orders , only: [:new, :create, :index, :show]
 resources :addresses , only: [:index, :edit, :create, :update, :destroy]
 get "customers" => redirect("/customers/sign_up")
 get '/genre/search' =>'genre_searches#search'
 get "customers" => redirect("/customers/sign_up")
 end
 
 
 namespace :admin do
 get '/' => 'homes#top'
 resources :items , only: [:index, :new, :create, :show,:edit, :update]
 resources :genres , only: [:index, :create, :edit, :update]
 resources :customers , only: [:index, :show, :edit, :update]
 resources :orders , only: [:show, :update]
 resources :order_details , only: [:update]
 end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer
  
  validates :post_code, presence: true
  validates :address, presence: true
  validates :name, presence: true
  
  def address_display
  '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
         validates :email, presence: true
         validates :password, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  
  def subtotal
    item.add_tax_price * amount
  end
  
  def self.calculate_total_price(cart_items)
    cart_items.inject(0) { |sum, item| sum + item.subtotal }
  end

  validates :item_id, presence: true
  validates :amount, presence: true
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable

 has_many :cart_items, dependent: :destroy
 has_many :items,through: :cart_item, dependent: :destroy
 has_many :orders, dependent: :destroy
 has_many :addresses, dependent: :destroy

 validates :email, presence: true, uniqueness: true
 validates :post_code, presence: true
 validates :address, presence: true
 validates :phone_number, presence: true
 validates :password, presence: true, length: { minimum: 6 }, on: :create # ユーザー新規登録時のみバリデーションを実行 
 validates :password_confirmation, presence: true, length: { minimum: 6 }, on: :create # ユーザー新規登録時のみバリデーションを実行 
 
 validates :last_name, :first_name, :last_name_kana, :first_name_kana, presence: { message: 'は必須項目です。' }
 validates :last_name, :first_name, format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/, message: 'は全角で入力して下さい。' }
 validates :last_name_kana, :first_name_kana, format: { with: /\A[\p{katakana}\p{blank}ー－]+\z/, message: 'はカタカナで入力して下さい。' }
 
 # is_activeがtrueならfalseを返すようにしている
  def active_for_authentication?
    super && (is_active == true)
  end
 
  def full_name
    "#{last_name} #{first_name}"
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  validates :name, presence: true
end

app/models/item.rb
class Item < ApplicationRecord

  has_one_attached :image
  enum status: { on_sale: 0, off_sale: 1 }
  
  has_many :cart_items, dependent: :destroy
  has_many :customers,through: :cart_items , dependent: :destroy
  has_many :order_details, dependent: :destroy
  has_many :orders,through: :order_details , dependent: :destroy
  
  belongs_to :genre
  
  def add_tax_price
    (self.price * 1.10).round
  end
  
  def self.active_items_count
    where(is_active: true).count
  end
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_details, dependent: :destroy
  has_many :items,through: :order_details, dependent: :destroy
  
  belongs_to :customer
  
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_payment: 0, payment_confirmation: 1, in_production: 2, preparing_to_ship: 3, shipped: 4 }

end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  
  def subtotal
    price * amount
  end
  
  enum making_status: { unprovable: 0, awaiting_production: 1, in_production: 2, production_completed: 3}
  
  
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   before_action :authenticate_admin!

   def top
     @orders = Order.page(params[:page])
   end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  
  def new
    @item = Item.new
  end
  
  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item)
    else
      flash.now[:alert] = "保存に失敗しました"
      render :new
    end
  end
  
  def show
    @item = Item.find(params[:id])
  end
  
  def index
    @items = Item.page(params[:page])
  end
  
  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
    redirect_to admin_item_path(@item.id)
    else
      render:edit
    end
  end
  
  private
  
  def item_params
    params.require(:item).permit(:image, :name, :introduction, :genre_id, :price, :status, :is_active)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/oder_details_helper.rb
module Admin::OderDetailsHelper
end

app/helpers/admin/oders_helper.rb
module Admin::OdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.css"/>
    <script src="https://cdn.jsdelivr.net/npm/swiper@8/swiper-bundle.min.js"></script>
  </head>

  <body class="d-flex flex-column vh-100", style="background-color: #FFFFEE;">
     <header class="shadow-sm", style="background-color: #ff8856;" >
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand text-white" href="/"><span>ながのCAKE</span></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
            <% if admin_signed_in? %>
            <li>
              <%= link_to '商品一覧', admin_items_path, class: 'nav-link text-white' %>
            </li>
            <li>
              <%= link_to '会員一覧', admin_customers_path, class: 'nav-link text-white' %>
            </li>
            <li>
              <%= link_to '注文履歴一覧', admin_path, class: 'nav-link text-white' %>
            </li>
            <li>
              <%= link_to 'ジャンル一覧', admin_genres_path, class: 'nav-link text-white' %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: 'nav-link text-white' %>
            </li>
            <% elsif customer_signed_in? %>
            <li class="nav-link text-white" style="margin-right: 200px;">
              ようこそ、<%= current_customer.last_name %>さん！
            </li>
            <li>
              <%= link_to 'マイページ', customers_my_page_path(current_customer.id), class: 'nav-link text-white' %>
            </li>
            <li>
              <%= link_to '商品一覧', items_path, class: 'nav-link text-white' %>
            </li>
            <li>
              <%= link_to 'カート', cart_items_path, class: 'nav-link text-white' %>
            </li>
            <li>
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-white' %>
            </li>
            <% else %>
            <li>
              <%= link_to 'About', about_path, class: 'nav-link text-white' %>
            </li>
            <li>
              <%= link_to '商品一覧', items_path, class: 'nav-link text-white' %>
            </li>
            <li>
              <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-white' %>
            </li>
            <li>
              <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-white' %>
            </li>
            <% end %>
            </ul>
          </div>
        </div>
      </nav>
    </header>

    <main class="mb-auto">
    <%= yield %>
    </main>

    <fotter class="container-fluid text-dark container-fluid", style="background-color: #ff8856;">
        <div class="row">
          <p class="col-auto mx-auto py-4">CopyRight Infratop.inc</p>
        </div>
    </fotter>
  </body>
</html>